# Language specifics
language: php
php:
  - '5.6'
  - '7.0'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

# Allow failures on nightly build
matrix:
  allow_failures:
   - php: nightly
   - php: hhvm

# PHP unit script
script: phpunit --coverage-text --coverage-clover=coverage.clover

# After running tests
after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi


# Notifications configuration
notifications:
  email:
      recipients:
        - stolkchris@gmail.com
      on_success: change
      on_failure: always
