# Language specifics
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer dump-autoload

# Allow failures on nightly build
matrix:
  allow_failures:
   - php: nightly

# PHP unit script
script: phpunit --coverage-text --coverage-clover=coverage.xml

# Notifications configuration
notifications:
  email:
      recipients:
        - stolkchris@gmail.com
      on_success: change
      on_failure: always