# Language specifics
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

# Allow failures on nightly build
matrix:
  allow_failures:
   - php: nightly

# PHP unit script
script: phpunit --configuration phpunit.xml --coverage-text

# Notifications configuration
notifications:
  email:
      recipients:
        - stolkchris@gmail.com
      on_success: change
      on_failure: always